In [1]:
import numpy as np
import pandas as pd

In [2]:
#empty and full numpy array
emp = np.empty(0)
full = np.full((3,4),(7))
emp, full

(array([], dtype=float64),
 array([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]))

In [3]:
#numpy array with zeros
zer = np.full((5,5), 0)
zer

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
#numpy array with ones
zer = np.full((5,5), 1)
zer

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
arr = np.random.randint(0,100, (5,3))


arr

array([[12, 73, 10],
       [34, 84, 54],
       [53, 71, 18],
       [ 0,  3,  9],
       [17, 15, 37]])

In [6]:
row = [17,80,15]
np.all(np.isin(arr,row).reshape(arr.shape), axis=1)

array([False, False, False, False, False])

In [7]:
#remove non numeric values
arr = np.array([["hi","hi","no"],
      [10,2,4],
      [20,0,"w"],
      [12,2,4]])
non_num = ~np.core.defchararray.isdigit(np.asarray(arr, dtype=str))
num_arr = arr[~np.any(non_num, axis=1)]
num_arr

array([['10', '2', '4'],
       ['12', '2', '4']], dtype='<U11')

In [8]:
#
arr = np.array([[[1,2,3]]])
no1d = np.squeeze(arr, axis=1)
no1d

array([[1, 2, 3]])

In [9]:
#frequency 
arr = np.array([1, 2, 3, 2, 4, 2, 5, 2])
count = np.count_nonzero(arr == 2)
count

4

In [10]:
#most frequent number
np.argmax(np.bincount(arr))

2

In [11]:
#combine vstack and hstack
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3], [3,4,5], [6,7,8]])
comb = np.vstack((arr,arr1))
combh = np.hstack((arr.reshape(-1,1), arr1))
comb, combh

(array([[1, 2, 3],
        [1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1, 1, 2, 3],
        [2, 3, 4, 5],
        [3, 6, 7, 8]]))

In [12]:
# 5 numpy functions
np.percentile (#computes the q-th percentile of the data along the specified axis)
np.diff (#calculates the n-th discrete difference along a given axis)
np.searchsorted (#finds the indices where elements should be inserted to maintain order. It's helpful for performing binary searches)
np.lexsort (# performs an indirect sort on multiple keys. It can be used to sort several arrays based on different sorting criteria.)
np.select (# returns an array drawn from elements in choicelist, depending on conditions)


SyntaxError: unexpected EOF while parsing (520560447.py, line 6)

In [13]:
arr = np.random.randint(2, 100, 30)
arr

array([12, 63, 36, 11, 29, 56, 35, 42, 17, 36, 48, 86, 51, 54, 31, 51, 87,
       76, 72, 32, 76, 58,  9, 23, 17, 52,  6, 21, 64, 24])

In [14]:
#function 1 np.percentile
per = np.percentile(arr, 75)
per
#calculates the 75th percentile of the given array 
# needs two arguments first the array and second the percetile we want to calculate

57.5

In [15]:
#functiion 2 np.diff
diff = np.diff(arr[0:10])
diff
#calculates the difference between indexes one by one and using first the latter index first as in 1st index is subtracted from 0


array([ 51, -27, -25,  18,  27, -21,   7, -25,  19])

In [16]:
#function 3 np.searchsorted
sort = np.searchsorted(arr,3)
sort
#gives the index at which a value should be inserted to maintain the sorting order.

0

In [21]:
import string
characters = np.array(list(string.ascii_letters + string.digits + '!@#$%^&*()'))
char_arr = np.random.choice(characters, size=30)
char_arr

array(['^', 'D', '0', 'X', '!', 'a', '1', '1', '4', 'v', 'd', 'G', 'X',
       'm', 'O', 'i', 'S', ')', 'C', '6', 'Z', '&', 'b', 'Y', 'I', 'F',
       'B', 'C', 'q', 'h'], dtype='<U1')

In [24]:
#function 4 np.lexsort
arr2 = np.array([2, 3, 1, 2, 3, 1, 4, 3, 4])
char_arr1 = np.array(['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c'])
lsort = np.lexsort((arr2, char_arr1))
lsort
#sorts the values based on multiple keys on multiple arrays in lexicographic order and returns indices 
#145 comes before 146 and cat is before catalog as cat is shorter
#the sorting is done based on char_arr1 and if there is a tie it uses the arr2 to sort but based on the index where the tie is

array([0, 3, 6, 1, 4, 7, 2, 5, 8], dtype=int64)

In [32]:
#function 5 np.select
selection = np.select([arr>10,arr<=10], [0, 10], 1000)
arr,selection
#replaces the values based on conditions as first argument, values to replace with as second argument and 
#default values if condition not satisfied.

(array([12, 63, 36, 11, 29, 56, 35, 42, 17, 36, 48, 86, 51, 54, 31, 51, 87,
        76, 72, 32, 76, 58,  9, 23, 17, 52,  6, 21, 64, 24]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0, 10,  0,  0,  0, 10,  0,  0,  0]))